//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Создание_БД.diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        public int DeliveryID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> DeliveryIDate { get; set; }
        public Nullable<int> DeliveryAddress { get; set; }
    
        public virtual ORDER ORDER { get; set; }
    }
}
