//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Создание_БД.diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> TotalaMount { get; set; }
        public int Stanus { get; set; }
        public int ProductId { get; set; }
    
        public virtual DELIVERY DELIVERY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual User User { get; set; }
    }
}
